# Time Complexity: O(V + E)
# - Reversing the graph: O(E)
# - Initial indegree computation: O(E)
# - BFS traversal over all nodes and edges: O(V + E)
# - Sorting result: O(V log V)

# Space Complexity: O(V + E)
# - rev_adj takes O(V + E)
# - indegree and queue take O(V)
# - topo list takes O(V)
